GET http://localhost:5000/memes?id=617d9ae1b0bab9de82365b78
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxN2NkMDY1YzIyNTMwM2I2MjkyM2E1NSIsImlhdCI6MTYzNTY4NzMzNywiZXhwIjoxNjM1Njg4NTM3fQ.72wstF156ycvLFynLCXel3RrOGunRUa7-YW6T0-TVh8
###

###

POST http://localhost:5000/auth-token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzU1NjQ1NzF9.w4dyqfQ71lujO6WURVnGXUtCQUAQikfpaTA3CLgD7T4"
}

###

POST http://localhost:5000/user-add
Content-Type: application/json

{
    "name": "admin",
    "email": "gkprmr@gmail.com",
    "password": "developer"
}

###

POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "gkprmr@gmail.com",
    "password": "developer"
}

###

POST https://meme-station-api.herokuapp.com/login
Content-Type: application/json

{
    "email": "gkprmr@gmail.com",
    "password": "developer"
}

###

POST http://localhost:5000/upload
Content-Type: application/json

{
    "fdsf": "fdsfdsf"
}

################################

POST https://meme-station-api.herokuapp.com/memes
