POST http://localhost:5000/user-login
Content-Type: application/json

{
    "email": "gkprmr@gmail.com",
    "password": "developer"
}
###

GET http://localhost:5000/memes?folderId=617f86619863de2985761902
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxN2NkMDY1YzIyNTMwM2I2MjkyM2E1NSIsImlhdCI6MTYzNTkxOTYyNCwiZXhwIjoxNjM2NTI0NDI0fQ.1hY55nut83F7KTidYR4-soNQ1PEUmRxzkeE4JBiYUNs

###

DELETE http://localhost:5000/likes/617fe21736790976992176ac
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxN2NkMDY1YzIyNTMwM2I2MjkyM2E1NSIsImlhdCI6MTYzNTkxNDk5NSwiZXhwIjoxNjM1OTE2MTk1fQ.Oe2n6sU8SrzHDBxsvob8cM985xJulmEb89Lz8EuKLMY

###

DELETE http://localhost:5000/save/617fe21736790976992176ac
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxN2NkMDY1YzIyNTMwM2I2MjkyM2E1NSIsImlhdCI6MTYzNTkxMDUzMywiZXhwIjoxNjM1OTExNzMzfQ.VBdG04cps4tNvYQkLCHSSPE2Nep54wyLLoxBAVXQxZw

###

DELETE http://localhost:5000/folders/6181a57ab939e2c4633a8f8b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxN2NkMDY1YzIyNTMwM2I2MjkyM2E1NSIsImlhdCI6MTYzNTkwNzg4OSwiZXhwIjoxNjM1OTA5MDg5fQ.F-D9gvxp_fVVOg7cQHe7XQ_wuiixHLaS0FXx3EusXn4

###

DELETE http://localhost:5000/save/617fe21736790976992176ac
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxN2NkMDY1YzIyNTMwM2I2MjkyM2E1NSIsImlhdCI6MTYzNTkxMDUzMywiZXhwIjoxNjM1OTExNzMzfQ.VBdG04cps4tNvYQkLCHSSPE2Nep54wyLLoxBAVXQxZw

###

GET http://localhost:5000/save?memeId=617fe21736790976992176ac
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxN2NkMDY1YzIyNTMwM2I2MjkyM2E1NSIsImlhdCI6MTYzNTkwNTg4NCwiZXhwIjoxNjM1OTA3MDg0fQ.M-ztEXD0aQLoF-c5929SVcNvuf6XzE8XnyFfsjXDTnQ

###


DELETE http://localhost:5000/save?memeId=617fe21736790976992176ac
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxN2NkMDY1YzIyNTMwM2I2MjkyM2E1NSIsImlhdCI6MTYzNTkwNzExNSwiZXhwIjoxNjM1OTA4MzE1fQ.gbad5eQh8oDzx2iOhgYT0HEUEyuPyq-gBRwNJJXFKlg

###


GET https://meme-station-api.herokuapp.com/save
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxN2NkMDY1YzIyNTMwM2I2MjkyM2E1NSIsImlhdCI6MTYzNTkwOTI2MywiZXhwIjoxNjM1OTEwNDYzfQ.R_ndAAU09ar-H92TROXJrJKHLlBY7fkYN1C0C26iMLI
Content-Type: application/json

###


GET https://meme-station-api.herokuapp.com/memes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxN2NkMDY1YzIyNTMwM2I2MjkyM2E1NSIsImlhdCI6MTYzNTkwOTI2MywiZXhwIjoxNjM1OTEwNDYzfQ.R_ndAAU09ar-H92TROXJrJKHLlBY7fkYN1C0C26iMLI

###

POST http://localhost:5000/auth-token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzU1NjQ1NzF9.w4dyqfQ71lujO6WURVnGXUtCQUAQikfpaTA3CLgD7T4"
}

###

POST http://localhost:5000/user-register
Content-Type: application/json

{
    "name": "Test Example",
    "email": "test@example.com",
    "password": "developer"
}

###

GET https://meme-station-api.herokuapp.com/user-current
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxN2NkMDY1YzIyNTMwM2I2MjkyM2E1NSIsImlhdCI6MTYzNTg1NjQ2MywiZXhwIjoxNjM1ODU3NjYzfQ.AKg14hdPpLnR0V-0BB2w0hILvX9N1_6scTZDK1t363U

###

POST http://localhost:5000/user-login
Content-Type: application/json

{
    "email": "gkprmr@gmail.com",
    "password": "developer"
}

###

POST https://meme-station-api.herokuapp.com/user-login
Content-Type: application/json

{
    "email": "gkprmr@gmail.com",
    "password": "developer"
}

###

POST http://localhost:5000/upload
Content-Type: application/json

{
    "fdsf": "fdsfdsf"
}

###

GET http://localhost:5000/folders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxN2NkMDY1YzIyNTMwM2I2MjkyM2E1NSIsImlhdCI6MTYzNTc0NzIyNCwiZXhwIjoxNjM1NzQ4NDI0fQ.SeNX1COpdoF9LXALx-9hvqQteuSORkA4y4BbVwMROVQ

###

###

POST http://localhost:5000/folders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxN2NkMDY1YzIyNTMwM2I2MjkyM2E1NSIsImlhdCI6MTYzNTc0NzIyNCwiZXhwIjoxNjM1NzQ4NDI0fQ.SeNX1COpdoF9LXALx-9hvqQteuSORkA4y4BbVwMROVQ

{
    "userId": 1,
    "title": "Dank Memes",
    "description": "Collections of dank memes",
    "privacy": "public"
}
###

POST https://meme-station-api.herokuapp.com/memes




